config/routes.rb
Rails.application.routes.draw do
  root 'application#base'
  get '/projects', to: 'projects#index'
  resources 'posts', only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :partial, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def base
    @post = Post.last
    @homepage = true
    render :home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
    @posts = Post.all
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @post = Post.last
    @projects = true
    render :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "KYLE HEPPENSTALL", root_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "PROJECTS", projects_path, class: "text" %></li>
        <li><%= link_to "BLOG", post_path(@post), class: "text" %></li>
        <li><%= link_to "", "https://github.com/kheppenstall", class: "fa fa-github fa-fw" %></li>
        <li><%= link_to "", "mailto:kyle.heppenstall@gmail.com", class: "fa fa-envelope" %></li>
        <li><%= link_to "", "https://www.linkedin.com/in/kyle-heppenstall", class: "fa fa-linkedin"%></li>
      </ul>
    </div>
  </div>
</nav>

app/views/application/home.html.erb
<div class="center">
  <img src="headshot.jpg" class="img-circle" alt="Headshot" width="250" height="auto">
  <p class="intro-text">
    Hello, I'm Kyle. I am a
    <br>software developer,
    <br>educator, 
    <br>math enthusiast,
    <br>and rock climber.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

    <body class= <%= "homepage" if @homepage %> <%= "projects" if @projects %> >
      <%= render partial: "navbar" %>
      <%= yield %>
  </body>
</html>

app/views/posts/_first_six_weeks.html.erb
<p>In October I began the 7-month Back-End Engineering Program at the Turing School of 	Software and Design. After three years of teaching algebra to 8th graders in Denver, I decided to enroll at Turing and make a career switch into software development.  Although life is notably less exciting among adults than 13-year olds, so far I could not be more pleased with my experience at Turing. </p>
<p>Our first 6 weeks focused on learning Ruby. We started with the basics of object-oriented programming and fundamental ruby syntax before progressing through enumerables and test-driven development. I started off a testing skeptic (and mainly wrote them retroactively for the first few projects) before succumbing to the pressure of my instructors. And by the end of the module I reluctantly started to grasp the importance of testing in good design. </p>
<p>Turing’s curriculum was stacked with interesting projects. Just in the first six weeks we wrote sorting algorithms, created a movie database with a binary search tree, made an autocomplete function with a tries, hosted a game on our first web server, and parsed data from csv files to conduct business analytics for an online store.</p>
<p>My favorite technical concept was our exploration of data structures. We made a binary search tree to store data on movies with the score of the movie as our key. The next week we used a trie to store all the English dictionary and create an autocomplete like your phone might use when writing a text message. Our progression from binary search trees to tries made sense since the fact the a node in a binary search tree can only have two children made its implementation far simpler. On the other hand, a node in a trie can have any number of children (we had up to 26 in our dictionary). The other key difference between binary search trees and tries is that nodes in a trie do not store their key. Instead nodes are defined by their position in the tree. In our example a node in the binary search tree stored its movie title and score. Conversely nodes in the trie were defined by the sequence of parent nodes leading down to the letter (the node for ‘g’ in the word ‘pig’ is defined by its placement below ‘pi’ in the trie). I love graphs so tune back in for another blog post discussing applications of different types of search trees.</p>
<p>What I enjoy about Turing even more than the projects is the community approach to learning. The culture at Turing places a special emphasis on collaborative learning and pairing sessions. The difficulty of the projects means that our entire cohort is often staying late to problem solve together. This collective struggle with such a diverse, passionate group of people has been the highlight of my first six weeks with Turing.</p>

app/views/posts/_rsa_encryption.html.erb
<h3>Framing the Problem</h3>

<p>RSA encryption is one of the most common ways to securely pass data through the web. Examples include SSL, SSH, digital signatures, and PGP. Writing this post helped me understand it better. Hopefully reading it will do the same for you.</p>

<p>Let's frame the problem first. We are the kingpins of our middle school's secret note passing ring. But, notes could be intercepted by teachers at any moment. Anyone in the school needs to be able to pass us a secret note, but no one else should know how to read it. So we want to an encryption system in which we are the only one who knows how to decrypt but anyone can follow our directions and encrypt a message. That way, even if messages are captured as they travel, the contents of the message will remain secret.</p>

<h3>Set Up The System (Make the Public and Private Keys)</h3>

<ol>
<li><p>Pick two prime numbers <code>p</code> and <code>q</code>. (I picked small ones since they make the examples easy to understand. In practical uses these primes are enormous.)</p>

<p><code>p = 3</code>
<code>q = 7</code></p></li>
<li><p>Find some products <code>n</code> and <code>t</code> using those primes.</p>

<pre><code>n = p * q = 7 * 3 = 21


t = (n - 1) * (q - 1) =  6 * 2 = 12

</code></pre></li>
<li><p>Pick an integer <code>e</code> that does not share any factors with <code>t</code>.</p>

<p>I choose <code>5</code> since it is small and shares no factors with <code>12</code>.</p>

<p><code>e = 5</code></p></li>
<li><p>The tough step! Find an integer <code>d</code> such that <code>d * e mod t = 1</code>.</p>

<p><a href="https://en.wikipedia.org/wiki/Modular_arithmetic">What is mod?</a></p>

<p>So we need to fill in the blank to make this statement true.</p>

<p><code>__ * 5 mod 12 = 1</code></p>

<p><code>17</code> works and is pretty small so let's choose 17.</p>

<p><code>d = 17</code></p>

<ol>
<li><p>Recap all those numbers we just found.</p>

<pre><code>p = 3
q = 7
n = 21
t = 12
e = 5
d = 17
</code></pre></li>
</ol></li>
</ol>

<h3>Publish the Directions (Public Key to Encrypt Message)</h3>

<p>Ok we did some math. Now we need to write some directions for everyone. Right now, no one knows how to use our encryption system. So let's spell it out for them so they can start sending us secret notes.</p>

<p>Disclaimer: The contents of a secret note must be a number.</p>

<p>DIRECTIONS
1. Change your message into a number somehow. Let's call your message <code>M</code>.
2. Use the formula <code>C = M^n mod e</code> to calcuate the encrypted message <code>C</code>.
    <code>M</code> is your message
    <code>
    n = 21
    e = 5
</code>
3. Write <code>C</code> on a note and pass it around.</p>

<p>Note: Keep the value of <code>d</code> secret.</p>

<h4>Example</h4>

<p>The secret message we want to pass <code>M</code> is <code>10</code>.</p>

<p>Given that our formula is <code>C = M^e mod n</code>, and <code>e = 5</code> and <code>n = 21</code>.</p>

<pre><code>`C = 10^5 mod 21 = 19`
</code></pre>

<p>So the content of the secret note <code>C</code> is <code>19</code>.</p>

<h3>Read the Messages (Private Key To Decrypt Message)</h3>

<p>Finally the secret notes are coming in. Let's assume everyone followed our directions when encrypting the message. To decrypt we use our private key, <code>n</code> and <code>d</code>. We will plug in the value of the secret message <code>C</code> into this formula to uncover the original secret message <code>M</code>.</p>

<p><code>M = C^d mod n</code></p>

<h4></a>Example</h4>

<p>The encrypted message <code>C</code> is <code>19</code> (from the example above).</p>

<p>To find the original message <code>M</code>, we use the formula <code>M = C^d mod n</code>, with <code>d = 17</code> and <code>n = 21</code>.</p>

<pre><code>`M = 19^17 mod 21 = 10`
</code></pre>

<p>We found <code>10</code>, the same number we started with!</p>

<h3>Sum it Up</h3>

<p>Although middle school kids are not lining up to use RSA encryption to pass secret notes, RSA encryption is used extensively to transmit private data over the Internet. The public key <code>n</code> and <code>e</code> can be published and the private key <code>n</code> and <code>d</code> is nearly impossible to find when the starting primes <code>p</code> and <code>q</code> are large enough. This creates a useful one-way information track where anyone can encrypt but only the server-side with the private key can decrypt.</p>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h2> <%= @post.title %> </h2>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class = "blog-post">
        <%= render @post.partial %>
        
      </div>
    </div>

    <div class="col-md-4">
      <div class="blog-index">
        <h4>All Posts</h4>
        <% @posts.each do |post| %>
          <%= link_to post.title, post_path(post) %><br>
        <% end %>        
      </div>
    </div>

  </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <h2>PROJECTS</h2>
</div>

<div class="container">
  <div class="row">

    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="http://media.istockphoto.com/photos/new-idea-light-bulb-on-blackboard-picture-id518223706?k=6&m=518223706&s=170667a&w=0&h=EJGmz9HEn2b8TpAZqYevzAGeyIOtMpYw1Q5NKvKKDZg=" alt="">
        <div class="caption">
        <h4>Idea Box</h4>
        <p>
          Web application to record and track ideas. Ideas have category tags and images. Individual Turing school project focusing  on authentication and authorization. Requires a user to login and has an admin to manage category tags and images.</p>
          <%= link_to "View on Github", "https://github.com/kheppenstall/idea_box", class: "btn-sm btn-default"%>
          <%= link_to "Heroku Link", "https://ancient-inlet-69343.herokuapp.com/", class: "btn-sm btn-default"%>
        </div>
      </div>
    </div>


    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="https://americanlibrariesmagazine.org/wp-content/uploads/2012/12/background_jobs4web.jpg" alt="">
        <div class="caption">
        <h4>Job Tracker</h4>
        <p>
          Web application to organize contacts, companies, comments, and categories for jobs. One of my first rails projects at Turing with CRUD functionality and postgres database.</p>
          <%= link_to "View on Github", "https://github.com/kheppenstall/job-tracker", class: "btn-sm btn-default"%>
          <%= link_to "Heroku Link", "https://powerful-tor-30592.herokuapp.com/dashboard", class: "btn-sm btn-default"%>
        </div>
      </div>
    </div>

    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="http://cf.ydcdn.net/1.0.1.64/images/wordfinder-background.jpg" alt="">
        <div class="caption">
        <h4>Complete Me</h4>
        <p>
          Autocomplete function written in Ruby. Project has a trie data structure to populate a dictionary and make word suggestions given a fragment. Paired project completed during my first month at Turing.</p>
          <%= link_to "View on Github", "https://github.com/kheppenstall/complete_me/tree/kyle_complete_me", class: "btn-sm btn-default"%>
        </div>
      </div>
    </div>

  </div>
</div>